### ISSUE TITLE
EJERCICIOS_PROPOSICIONES_LOGICAS_MAYRA_GLEZ_1AS

### ISSUE THREAD

**Issue by mayraglez917** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-mayraglez917#1]
[Practica_Ejercicios_Proposiciones_Mayra_Glez_1AS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-mayraglez917/files/13289668/Practica_Ejercicios_Proposiciones_Mayra_Glez_1AS.pdf)

**Comment by elisa1223** [comment]
Portada: 25%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 25%
Resultados y conclusiones: 25%

Calificación final: 20/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
